// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRimI5sh81w31sVBaOiKWBr24cPw5SC_A',
    appId: '1:334748011560:web:966f0d8dffb6cf13ac791d',
    messagingSenderId: '334748011560',
    projectId: 'auctify-86815',
    authDomain: 'auctify-86815.firebaseapp.com',
    storageBucket: 'auctify-86815.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPeZII00dQO5Y8LpR2XKsXfoJW65E5qE',
    appId: '1:334748011560:android:975d8e6034a30edfac791d',
    messagingSenderId: '334748011560',
    projectId: 'auctify-86815',
    storageBucket: 'auctify-86815.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimM8lstgvzG5jjtInyuIy7hdoHZZ2GyA',
    appId: '1:334748011560:ios:1e0e2721294ea01fac791d',
    messagingSenderId: '334748011560',
    projectId: 'auctify-86815',
    storageBucket: 'auctify-86815.firebasestorage.app',
    androidClientId: '334748011560-koev3u3hgjl7l2edhsq30ce29144eqvg.apps.googleusercontent.com',
    iosClientId: '334748011560-4kr8si8hbe0tu892r36voequ1as1tuuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctifyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAimM8lstgvzG5jjtInyuIy7hdoHZZ2GyA',
    appId: '1:334748011560:ios:1e0e2721294ea01fac791d',
    messagingSenderId: '334748011560',
    projectId: 'auctify-86815',
    storageBucket: 'auctify-86815.firebasestorage.app',
    androidClientId: '334748011560-koev3u3hgjl7l2edhsq30ce29144eqvg.apps.googleusercontent.com',
    iosClientId: '334748011560-4kr8si8hbe0tu892r36voequ1as1tuuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctifyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRimI5sh81w31sVBaOiKWBr24cPw5SC_A',
    appId: '1:334748011560:web:1c6bf9d2ce4fb60bac791d',
    messagingSenderId: '334748011560',
    projectId: 'auctify-86815',
    authDomain: 'auctify-86815.firebaseapp.com',
    storageBucket: 'auctify-86815.firebasestorage.app',
  );
}
